spring.application.name=formLogin
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp


spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=formLogin
spring.datasource.password=formLogin
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.formLogin.domain
mybatis.config-location=classpath:mybatis-config.xml
